apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-storage-pvc
  labels:
    app: natours
    role: static-disk
    tier: file-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""

  resources:
    requests:
      storage: 1Gi

  selector:
    matchLabels:
      app: natours
      role: static-disk
      tier: file-storage
