version: '3.9'

services:
  broker:
    container_name: broker
    image: rabbitmq:3-management-alpine
    restart: on-failure
    networks:
    - backend
    env_file:
    - .envs/.env
    ports:
    - 15672:15672

  db:
    build:
      context: ./postgres
    container_name: db
    networks:
    - backend
    restart: on-failure
    env_file: .envs/.env.db
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data

  flower:
    container_name: flower
    depends_on:
    - worker
    - broker
    image: plots418890/natours_backend:dev
    networks:
    - backend
    restart: on-failure
    entrypoint: ['${PROJECT_PATH?Variable not set}/commands/entrypoint.flower.sh']
    env_file:
    - .envs/.env
    ports:
    - 5555:5555
    volumes:
    - ./src:${PROJECT_PATH?Variable not set}


  resultdb:
    container_name: resultdb
    depends_on:
    - broker
    - webserver
    - worker
    entrypoint: [ 'redis-server' ]
    image: redis:7.0-rc-alpine
    networks:
    - backend
    restart: on-failure

  reverseproxy:
    container_name: reversproxy
    depends_on:
    - webserver
    image: nginx:1.21.6-alpine
    networks:
    - backend
    - frontend
    restart: on-failure
    ports:
      - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - webserver_static:${PROJECT_PATH?Variable not set}/static
    - webserver_media:${PROJECT_PATH?Variable not set}/media

  webserver:
    entrypoint: [ '${PROJECT_PATH?Variable not set}/commands/entrypoint.sh' ]
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    container_name: webserver
    env_file:
    - .envs/.env
    depends_on:
    - db
    - broker
    image: plots418890/natours_backend:dev
    networks:
    - backend
    restart: on-failure
    volumes:
    - ./src:${PROJECT_PATH?Variable not set}
    - webserver_static:/home/app/src/static
    - webserver_media:/home/app/src/media

  worker:
    container_name: worker
    entrypoint: [ '${PROJECT_PATH?Variable not set}/commands/entrypoint.celery.sh' ]
    env_file:
    - .envs/.env
    volumes:
    - ./src:${PROJECT_PATH?Variable not set}
    depends_on:
    - broker
    - db
    image: plots418890/natours_backend:dev
    networks:
    - backend
    restart: on-failure

volumes:
  pgdata:
  webserver_media:
  webserver_static:

networks:
  backend:
    name: 'webservernet'
  frontend:
    external:
      name: 'natoursnet'
