version: '3.9'

services:
  broker:
    container_name: broker
    image: rabbitmq:3-management-alpine
    restart: on-failure
    networks:
      - backend

  db:
    build:
      context: ./postgres
    container_name: db
    networks:
      - backend
    restart: on-failure

  flower:
    container_name: flower
    depends_on:
      - worker
      - broker
    image: plots418890/natours_backend:dev
    networks:
      - backend
    restart: on-failure

  resultdb:
    container_name: resultdb
    depends_on:
      - broker
      - webserver
      - worker
    entrypoint: [ 'redis-server' ]
    image: redis:7.0-rc-alpine
    networks:
      - backend
    restart: on-failure

  reverseproxy:
    container_name: reversproxy
    depends_on:
      - webserver
    image: nginx:1.21.6-alpine
    networks:
      - backend
      - frontend
    restart: on-failure

  webserver:
    build:
      context: .
    container_name: webserver
    depends_on:
      - db
      - broker
    image: plots418890/natours_backend:dev
    networks:
      - backend
    restart: on-failure
 
  worker:
    container_name: worker
    depends_on:
      - broker 
      - db
    image: plots418890/natours_backend:dev
    networks:
      - backend
    restart: on-failure

  
networks:
  backend:
    name: 'webservernet'
  frontend:
    external:
      name: 'uinet'
