# Generated by Django 4.0.2 on 2022-02-23 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('natours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Booking price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Booking creation datetime')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Booking payment status')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='natours.tour', verbose_name='Booking belong to the tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Booking belong to the user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
