apiVersion: v1
kind: Service
metadata:
  name: media-storage
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: natours
    role: media-disk
    tier: file-storage
