apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-storage
spec:
  template:
    metadata:
      labels:
        app: natours
        role: static-disk
        tier: file-storage
    spec:
      containers:
        - name: natours-static-nfs-container
          image: gcr.io/google_containers/volume-nfs:0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: static-storage
      volumes:
        - name: static-storage
          gcePersistentDisk:
            pdName: gce-static-nfs
            fsType: ext4

  replicas: 1

  selector:
    matchLabels:
      app: natours
      role: static-disk
      tier: file-storage