apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-sc
provisioner: kubernetes.io/gce-pd

reclaimPolicy: Retain
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none