apiVersion: v1
kind: ConfigMap
metadata:
  name: db-cm
  labels:
    app: natours
    role: db
    tier: backend

data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "natours"
  PGDATA: "/var/lib/postgresql/data/pgdata"