apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-cm
  labels:
    app: natours
    role: webserver
    tier: backend

data:
  DJANGO_SETTINGS_MODULE: "apps.config.settings.dev"
  # in minutes
  ACCESS_TOKEN_LIFETIME: "5"
  # in days
  REFRESH_TOKEN_LIFETIME: "30"

  DATABASE_USER: "postgres"
  DATABASE_NAME: "natours"
  DATABASE_HOST: "db-clusterip"
  DATABASE_PORT: "5432"

  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_SENT_FROM: "natours@admin.io"

  PASSWORD_RESET_TIMEOUT: "600"

  RABBITMQ_DEFAULT_USER: "brokeradmin"
  BROKER_PORT: "5672"
  BROKER_HOST: "broker-clusterip"
  
  RESULT_BACKEND_HOST: "resultdb-clusterip"
  RESULT_BACKEND_PORT: "6379"

  CLIENT_BASE_URL: "https://www.natours-club.site"
  ALLOWED_HOSTS: "api.natours-club.site;"
  CORS_ALLOWED_ORIGINS: "https://natours-club.site;https://www.natours-club.site;http://ui-app-nodeport"
