apiVersion: v1
kind: Service
metadata:
  name: broker-clusterip
  labels:
    app: natours
    role: broker
    tier: backend
spec:
  ports:
    - targetPort: 5672
      port: 5672

  selector:
    app: natours
    role: broker
    tier: backend