apiVersion: v1
kind: Service
metadata:
  name: db-clusterip
  labels:
    app: natours
    role: db
    tier: backend
spec:
  ports:
    - targetPort: 5432
      port: 5432

  selector:
    app: natours
    role: db
    tier: backend