apiVersion: v1
kind: Service
metadata:
  name: db-loadbalancer
spec:
  externalName: postgres
  ports:
    - port: 5432
      targetPort: 5432

  type: LoadBalancer

  selector:
    app: natours
    role: db
    tier: backend