apiVersion: v1
kind: Service
metadata:
  name: flower-loadbalancer
  labels:
    app: natours
    role: tasks-monitoring
    tier: monitoring
spec:
  externalName: flower
  ports:
    - targetPort: 5555
      port: 5555
      
  type: LoadBalancer

  selector:
    app: natours
    role: tasks-monitoring
    tier: monitoring
