apiVersion: v1
kind: Service
metadata:
  name: resultdb-clusterip
  labels:
    app: natours
    role: result-backend
    tier: backend

spec:
  ports:
    - port: 6379
      targetPort: 6379

  selector:
    app: natours
    role: result-backend
    tier: backend