apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-clusterip

spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80

  selector:
      app: natours
      role: reverseproxy
      tier: backend