apiVersion: v1
kind: Service
metadata:
  name: webserver-clusterip
  labels:
    app: natours
    role: webserver
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888

  selector:
    app: natours
    role: webserver
    tier: backend
